### PR TITLE
Update to 20.12.0

### PR DESCRIPTION
**Pull request by cho2**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Please update the kross tarball to 5.76

**Comment by tsdgeos** [comment]
Mentioning myself here so i can find it in github, sorry for being a newbie @tsdgeos

**Comment by tsdgeos** [comment]
I did it on https://github.com/flathub/org.kde.lokalize/pull/9 while waiting for other stuff to compile, hope you don't mind :)

**Comment by cho2** [comment]
Thanks

**Pull request closed without merging**
